app_code: bk_log_search
app_name: 日志检索
author: 蓝鲸智云
!!python/unicode 'date': '2017-05-16 12:17:19'
introduction: 蓝鲸智云日志检索产品是为了解决运维场景中查询日志难的问题而推出的一款Saas，基于业界主流的全文检索引擎，通过蓝鲸智云的专属agent进行日志采集，无需登录各台机器，集中管理所有日志。
is_use_celery: true
!!python/unicode 'language': python
libraries:
- name: kombu
  version: 3.0.35
version: 1.0.13
